# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:7.13.2
EXPOSE 9200
# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu